#' Density plot for flow cytometry
#'
#' @param file a standard CSV file generated by NovoExpress software
#' @param label label of sample
#' @param channel channel name in the CSV file
#' @param gate threshold
#' @param xlims two numeric values, specifying the lower limit and the upper limit of the scale
#' @param text.x text
#' @param lab.x x-axis label
#' @param lab.y y-axis label
#' @param title plot title
#' @param legend plot legend, the values can be "none"/"legend"
#' @param fill fill
#' @param color color
#' @param alpha alpha
#' @param fixed_ratio ratio of the x axis and y axis
#'
#' @return a ggplot2 plot
#' @export
#'
#' @examples
plotFC_1group <- function(file,
                          label,
                          channel,
                          gate = c(1,7),
                          xlims = c(0.5,8),
                          text.x = 7,
                          lab.x = NULL,
                          lab.y = "% of Max",
                          title = "xxx",
                          legend = "legend",
                          fill = "#939393",
                          color = "#939393",
                          alpha = 0.5,
                          fixed_ratio = 5.5){

  gate <- 10^gate
  breaks <- floor(xlims[2]-xlims[1]+1)
  xlims <- 10^xlims
  text.x <- 10^text.x



  exp <- read.csv(file = file, sep = ",", header = T, fill = T, check.names = F) %>%
    tibble::add_column(sample = label) %>%
    subset(select = c("sample", channel)) %>%
    magrittr::set_colnames(c("sample", "exp"))


  perc <- length(exp$exp[exp$exp > gate[1] & exp$exp < gate[2]])/length(exp$exp)
  perc <- round(perc*100, 2)


  exp <- exp[exp$exp > 0, ]

  p <- ggplot(exp, aes(x = exp))+
    geom_density(aes(y = after_stat(scaled)), fill = fill, color = color, alpha = alpha, adjust = 1/2)+
    annotate("segment", x = gate[1], y = 0.3, xend = gate[2], yend = 0.3, color = "black")+
    annotate("segment", x = gate[1], y = 0.28, xend = gate[1], yend = 0.32, color = "black")+
    annotate("segment", x = gate[2], y = 0.28, xend = gate[2], yend = 0.32, color = "black")+
    annotate("text", x = text.x, y = 0.4, label = paste0(label, "\n", perc, "%"))+
    labs(x = lab.x, y = lab.y)+
    ggtitle(title)+
    guides(color = legend, fill = legend)+
    scale_x_log10(breaks = scales::breaks_log(n = breaks, base = 10),
                  labels = scales::label_log(base = 10),
                  guide = "axis_logticks")+
    scale_y_continuous(breaks = seq(0,1, 0.2),
                       labels = scales::label_percent(suffix = ""))+
    theme_bw()+
    theme(legend.title = element_blank(),
          aspect.ratio = 1,
          plot.title = element_text(hjust = 0.5),
          panel.grid = element_blank(),
          axis.ticks.x = element_line(linewidth = 0.4),
          axis.ticks.y = element_line(linewidth = 0.4),
          axis.minor.ticks.x.bottom = element_line(linewidth = 0.2))+
    coord_fixed(xlim = c(xlims[1], xlims[2]), ylim = c(0,1.1), expand = F)

  p

}
