#' Gene expression plot for qPCR analysis
#'
#' @param file a table file of gene expression generated by QuantStudio software
#' @param gene genes to plot
#' @param geneLabel labels of genes
#' @param fill colors
#' @param groups groups
#' @param comparison comparison
#' @param style 1 or 2
#'
#' @return
#' @export
#'
#' @examples
plotQ_Tukey <- function(file, gene, geneLabel, fill, groups, comparison, style){
  require(rstatix)
  require(tidyverse)

  # load data
  exp <- read.table(file = file, sep = "\t", header = T, fill = T)
  exp <- data.frame(sample = exp$Sample.Name, gene = exp$Target.Name, rq = exp$RQ)
  exp <- na.omit(exp)
  exp$group <- gsub("_.*", "", exp$sample)

  # isolate interest gene and group
  exp_sub <- exp[exp$gene == gene & exp$group %in% groups,]
  exp_sub$group <- factor(exp_sub$group, levels = groups)

  # normalize
  mean_ctrl <- mean(exp_sub$rq[exp_sub$group == groups[1]])
  exp_sub$rq <- exp_sub$rq/mean_ctrl

  # stat
  res_aov <- aov(rq ~ group, data = exp_sub)
  res_tukey <- tukey_hsd(res_aov)
  res_tukey$groups <- paste(res_tukey$group1, res_tukey$group2, sep = "-")

  res_tukey <- lapply(comparison, function(x) {
    tuList <- res_tukey[grepl(groups[x[1]], res_tukey$groups) & grepl(groups[x[2]], res_tukey$groups), ]
    tuList$ppos <- mean(c(x[1],x[2]))
    tuList
  }) %>% Reduce(rbind, .)

  max <- max(exp_sub$rq)*1.1
  res_tukey$y = cumprod(c(max, rep(1.1, length(comparison)-1)))
  res_tukey$p.adj <- paste0("p = ", res_tukey$p.adj)

  if(style == 1){
    res_tukey$vline = res_tukey$y
    res_tukey$vline_end = res_tukey$y
  }
  if(style == 2){
    res_tukey$vline = res_tukey$y+0.02
    res_tukey$vline_end = res_tukey$y-0.02
  }

  exp_sum <- exp_sub %>%
    group_by(group) %>%
    summarise(mean = mean(rq),
              n = length(rq),
              sd = sd(rq),
              sem = sd/sqrt(n))

  p <- ggplot(exp_sum, aes(x = group, y = mean))+
    geom_bar(aes(fill = group), position = position_dodge(1), stat = "identity", color = "black", alpha = 0.6, width=0.6)+
    geom_errorbar(aes(x = group, ymin=mean-sem, ymax=mean+sem),
                  position = position_dodge(0.5), width=0.3, colour="black", alpha=0.9, linewidth =1)+
    geom_point(data = exp_sub, aes(y = rq, fill = group), shape = 21, size = 2, show.legend = FALSE, color = "black",
               position = position_jitterdodge(0.2, dodge.width = 1))+
    geom_segment(data = res_tukey, aes(x = group1, xend = group2, y = y, yend = y),linewidth = 0.3)+
    geom_segment(data = res_tukey, aes(x = group1, xend = group1, y = vline, yend = vline_end),linewidth = 0.3)+
    geom_segment(data = res_tukey, aes(x = group2, xend = group2, y = vline, yend = vline_end),linewidth = 0.3)+
    geom_text(data = res_tukey, aes(x = ppos-0.4, y = y*1.02, label = p.adj), size = 2, vjust = 0, hjust = 0, nudge_x = 0)+
    ggtitle(geneLabel)+
    scale_y_continuous(expand = c(0,0), limits = c(0,max(res_tukey$y)*1.1))+
    scale_x_discrete(expand = c(0,0))+
    scale_fill_manual(values = fill)+
    labs(x= "", y = "Relative mRNA expression")+
    theme_bw()+
    theme(legend.title = element_blank(),
          plot.title = element_text(hjust = 0.5),
          panel.grid = element_blank())

  p

}
