#' 2D plot for flow cytometry
#'
#' @param file a standard CSV file generated by NovoExpress software
#' @param label label of sample
#' @param channel channel name in the CSV file
#' @param xlims two numeric values, specifying the lower limit and the upper limit of the scale
#' @param ylims two numeric values, specifying the lower limit and the upper limit of the scale
#' @param gates two numeric values, specifying the gates
#' @param legend plot legend, the values can be "none"/"legend"
#' @param type plot type, the values can be "point"/"density"
#' @param alpha.point alpha of the point
#' @param alpha.density alpha of the density
#' @param size.point size of the point
#' @param size.density size of the density
#' @param bins.density bins of the density
#'
#' @return a ggplot2 plot
#' @export
#'
#' @examples
plotFC_2d <- function(file,
                      label = "none",
                      channel,
                      xlims = c(3,8),
                      ylims = c(2,7),
                      gates = c(4.1, 3.5),
                      legend = "none",
                      type = c("point", "density"),
                      alpha.point = 0.3,
                      alpha.density = 0.6,
                      size.point = 0.1,
                      size.density = 1,
                      bins.density = 50){
  xbreaks <- floor(xlims[2]-xlims[1]+1)
  ybreaks <- floor(ylims[2]-ylims[1]+1)
  xlims <- 10^xlims
  ylims <- 10^ylims
  gates <- 10^gates

  exp <- read.csv(file = file, sep = ",", header = T, fill = T, check.names = F) %>%
    tibble::add_column(sample = label) %>%
    subset(select = c("sample", channel)) %>%
    magrittr::set_colnames(c("sample", "exp1", "exp2"))

  exp <- exp[exp$exp1 > 0 & exp$exp2 > 0, ]

  perc <- c()
  perc[1] <- exp$sample[exp$exp1 > gates[1] & exp$exp2 > gates[2]] %>% length()/length(exp$sample)
  perc[2] <- exp$sample[exp$exp1 > gates[1] & exp$exp2 < gates[2]] %>% length()/length(exp$sample)
  perc[3] <- exp$sample[exp$exp1 < gates[1] & exp$exp2 < gates[2]] %>% length()/length(exp$sample)
  perc[4] <- exp$sample[exp$exp1 < gates[1] & exp$exp2 > gates[2]] %>% length()/length(exp$sample)

  perc <- round(perc*100, 2)


  p <- ggplot(exp, aes(x = exp1, y = exp2))

  if("point" %in% type){
    p <- p+rasterise(geom_point(size = size.point, alpha = alpha.point, color = "#2F89BE"), dpi = 300)
  }

  if("density" %in% type){
    p <- p+geom_density_2d(aes(color = after_stat(level)), contour_var = "ndensity",
                           bins = bins.density, linewidth = size.density, alpha = alpha.density)
  }

  p <- p+scale_x_log10(expand = c(0,0),
                       breaks = scales::breaks_log(n = xbreaks, base = 10),
                       labels = scales::label_log(base = 10),
                       guide = "axis_logticks")+
    scale_y_log10(expand = c(0,0),
                  breaks = scales::breaks_log(n = ybreaks, base = 10),
                  labels = scales::label_log(base = 10),
                  guide = "axis_logticks")+
    geom_vline(xintercept = gates[1])+
    geom_hline(yintercept = gates[2])+
    scale_color_stepsn(n.breaks = 20,colors = rev(c("#D73E50", "#E3504C", "#ED6247", "#F37346", "#F68D52",
                                                    "#F9A45C", "#FCB96A", "#FECB79", "#FCDD89", "#F6E98F",
                                                    "#ECEE95", "#E2EA9A", "#CDE39E", "#B9DCA1", "#A2D4A3",
                                                    "#8ACDA5", "#6DC6A6", "#59B2AC", "#4A9DB5", "#2F89BE")))+
    guides(color = legend)+
    annotate(geom = "text", label = perc[1], x = xlims[2]*0.7, y = ylims[2]*0.7, hjust = 1, vjust = 1)+
    annotate(geom = "text", label = perc[2], x = xlims[2]*0.7, y = ylims[1]*1.3, hjust = 1, vjust = 0)+
    annotate(geom = "text", label = perc[3], x = xlims[1]*1.3, y = ylims[1]*1.3, hjust = 0, vjust = 0)+
    annotate(geom = "text", label = perc[4], x = xlims[1]*1.3, y = ylims[2]*0.7, hjust = 0, vjust = 1)+
    theme_bw()+
    theme(legend.title = element_blank(),
          legend.key.height = unit(1, "cm"),
          aspect.ratio = 1,
          plot.title = element_text(hjust = 0.5),
          panel.grid = element_blank(),
          axis.title = element_blank(),
          axis.ticks.x = element_line(linewidth = 0.4),
          axis.ticks.y = element_line(linewidth = 0.4),
          axis.minor.ticks.x.bottom = element_line(linewidth = 0.2))+
    coord_fixed(xlim = c(xlims[1], xlims[2]), ylim = c(ylims[1], ylims[2]))

  p

}
