#' Gene expression plot for qPCR analysis
#'
#' @param file a table file of gene expression generated by QuantStudio software
#' @param genes genes to plot
#' @param groups two groups
#' @param title plot title
#' @param fill colors
#' @param label.group group labels
#' @param size.p font size for p value
#' @param angle.p angle for p value
#'
#' @return a ggplot2 bar plot
#' @export
#'
#' @examples
plotQ_t <- function(file, genes, groups, title, fill, label.group, size.p = 2, angle.p = 45){

  exp <- read.table(file = file, sep = "\t", header = T, fill = T)
  exp <- data.frame(sample = exp$Sample.Name, gene = exp$Target.Name, rq = exp$RQ)
  exp <- na.omit(exp)
  exp$group <- gsub("_.*", "", exp$sample)


  exp_sub <- exp[exp$gene %in% genes & exp$group %in% groups,]
  exp_sub$group <- factor(exp_sub$group, levels = groups)
  exp_sub$gene <- factor(exp_sub$gene, levels = genes)

  exp_sub <- split(exp_sub, exp_sub$gene)

  exp_sub <- lapply(exp_sub, function(x) {
    mean_ctrl <- mean(x$rq[x$group == groups[1]])
    x$rq <- x$rq/mean_ctrl
    x
  })


  exp_sum <- lapply(exp_sub, function(x) {
    group_by(x, group) %>%
      summarise(mean = mean(rq),
                n = length(rq),
                sd = sd(rq),
                sem = sd/sqrt(n)) %>%
      mutate(gene = unique(x$gene))
  }) %>% Reduce(rbind,.)


  res_t <- lapply(exp_sub, function(x) {
    t_test(x, rq ~ group)
  }) %>% Reduce(rbind,.)

  res_t <- data.frame(p = paste0("p = ", res_t$p),
                      x = 1:nrow(res_t),
                      line.x = 1:nrow(res_t)-0.25,
                      line.x.end = 1:nrow(res_t)+0.25)



  exp_sub <- Reduce(rbind,exp_sub)

  max <- max(exp_sub$rq)

  if(length(genes) == 1){
    p <- ggplot(exp_sum, aes(x = group, y = mean, fill = group))+
      geom_bar(position = position_dodge(1), stat = "identity", color = "black", alpha = 0.6, width=0.6)+
      geom_errorbar(aes(x = group, ymin=mean-sem, ymax=mean+sem),
                    position = position_dodge(1), width=0.3, colour="black", alpha=0.9, linewidth =1)+
      geom_point(data = exp_sub, aes(y = rq), shape = 21, size = 2, show.legend = FALSE, color = "black",
                 position = position_jitterdodge(0.2, dodge.width = 1))+
      geom_segment(data = res_t, aes(x = 1, xend = 2, y = max*1.05, yend = max*1.05),
                   linewidth = 0.3, inherit.aes = F)+
      geom_text(data = res_t, aes(x = 1.5, y = max*1.05, label = p),
                size = size.p, vjust = -0.5, hjust = 0.5, nudge_x = 0, angle = angle.p, inherit.aes = F)+
      ggtitle(title)+
      guides(fill = "none")+
      scale_y_continuous(expand = c(0,0), limits = c(0,max*1.3))+
      scale_x_discrete(expand = c(0,0))+
      scale_fill_manual(values = fill, labels = label.group)+
      labs(x= "", y = "Relative mRNA expression")+
      theme_bw()+
      theme(legend.title = element_blank(),
            plot.title = element_text(hjust = 0.5),
            panel.grid = element_blank())
  }else{
    p <- ggplot(exp_sum, aes(x = gene, y = mean, fill = group))+
      geom_bar(position = position_dodge(1), stat = "identity", color = "black", alpha = 0.6, width=0.6)+
      geom_errorbar(aes(x = gene, ymin=mean-sem, ymax=mean+sem),
                    position = position_dodge(1), width=0.3, colour="black", alpha=0.9, linewidth =1)+
      geom_point(data = exp_sub, aes(y = rq), shape = 21, size = 2, show.legend = FALSE, color = "black",
                 position = position_jitterdodge(0.2, dodge.width = 1))+
      geom_segment(data = res_t, aes(x = line.x, xend = line.x.end, y = max*1.05, yend = max*1.05),
                   linewidth = 0.3, inherit.aes = F)+
      geom_text(data = res_t, aes(x = x, y = max*1.05, label = p),
                size = size.p, vjust = -0.5, hjust = 0, nudge_x = 0, angle = angle.p, inherit.aes = F)+
      ggtitle(title)+
      scale_y_continuous(expand = c(0,0), limits = c(0,max*1.3))+
      scale_x_discrete(expand = c(0,0))+
      scale_fill_manual(values = fill, labels = label.group)+
      labs(x= "", y = "Relative mRNA expression")+
      theme_bw()+
      theme(legend.title = element_blank(),
            plot.title = element_text(hjust = 0.5),
            panel.grid = element_blank())
  }



  p

}
