#' Density plot for flow cytometry
#' @description
#' The function is designed to generate a multi-sample density plot for flow cytometry assay
#'
#' @param files standard CSV files generated by NovoExpress software
#' @param labels labels
#' @param channel channel name in the CSV file
#' @param xlims two numeric values, specifying the lower limit and the upper limit of the scale
#' @param title plot title
#' @param fills colors used to fill the density
#' @param colors colors
#' @param alpha alpha
#' @param fixed_ratio ratio of the x axis and y axis
#' @param pos.label position of labels
#' @param nudge.label.y Vertical adjustment to nudge sample labels by
#' @param plot.perc logical, it controls whether to plot perc labels
#' @param nudge.perc.x horizontal adjustment to nudge perc labels by
#' @param nudge.perc.y vertical adjustment to nudge perc labels by
#' @param plot.MFI logical, it controls whether to plot MFI labels
#' @param nudge.MFI.x horizontal adjustment to nudge MFI labels by
#' @param nudge.MFI.y vertical adjustment to nudge MFI labels by
#' @param quantile.probs numeric vector of probabilities with values in 0-1
#'
#' @return a ggplot2 density plot
#' @export
#'
#' @examples
#' # none
#'
plotFC_multi <- function(files,
                         labels,
                         pos.label = 0.3,
                         nudge.label.y = 0.8,
                         plot.perc = F,
                         quantile.probs = 0.99,
                         nudge.perc.x = 3,
                         nudge.perc.y = 0.8,
                         plot.MFI = F,
                         nudge.MFI.x = 3,
                         nudge.MFI.y = 0.8,
                         channel,
                         xlims,
                         title = "xxx",
                         fills, colors, alpha,
                         aspect.ratio = 1){


  breaks <- xlims[2]-xlims[1]+1
  label.x <- 10^(xlims[1]+pos.label)
  xlims <- 10^xlims

  expList <- list()

  for (i in 1:length(files)) {
    expList[[i]] <- read.csv(file = files[i], sep = ",", header = T, fill = T, check.names = F) %>%
      tibble::add_column(sample = labels[i]) %>%
      subset(select = c("sample", channel)) %>%
      magrittr::set_colnames(c("sample", "exp"))
  }

  exps <- Reduce(rbind, expList)
  exps <- exps[exps$exp > 0, ]

  # MFI
  sum <- exps %>%
    dplyr::group_by(sample) %>%
    dplyr::summarise(MFI = round(mean(exp), 0))

  # positive cells
  if(plot.perc){
    lim_f <- quantile(exps$exp[exps$sample == labels[1]], probs = quantile.probs)

    percList <- c()
    for (i in 1:length(labels)) {
      exp_sub <- exps[exps$sample == labels[i],]
      perc <- length(exp_sub$exp[exp_sub$exp > lim_f])/length(exp_sub$exp)
      perc <- round(perc*100, 1)

      percList[i] <- perc

    }
  }

  labelMeta <- data.frame(label = labels, x = label.x)

  if(plot.perc){
    labelMeta$perc <- paste0(percList, " %")
  }
  if(plot.MFI){
    labelMeta$MFI <- sum$MFI[match(labelMeta$label, sum$sample)] %>% format(big.mark = ",")
  }


  exps <- data.frame(sample = labels, addmin = xlims[1]-1, addmax = xlims[2]+1) %>%
    gather(add, exp, -sample) %>%
    subset(select = c("sample", "exp")) %>%
    rbind(exps) %>%
    tibble::remove_rownames()

  exps$sample <- factor(exps$sample, levels = rev(labels))

  p <- ggplot(exps, aes(x = exp, y = sample)) +
    ggridges::geom_density_ridges(aes(height = after_stat(scaled), fill = sample, color = sample),
                                  stat = "density",
                                  scale = 0.9,
                                  alpha = alpha,
                                  adjust =1/2,
                                  rel_min_height = 0) +
    scale_x_log10(expand = c(0,0),
                  breaks = scales::breaks_log(n = breaks, base = 10),
                  labels = scales::label_log(base = 10),
                  guide = "axis_logticks")+
    scale_y_discrete(expand = c(0, 0,0, 1))+
    scale_fill_manual(values = fills)+
    geom_text(data = labelMeta, mapping = aes(x = x, y = label, label = label), hjust = 0, nudge_y = nudge.label.y, inherit.aes = F)+
    ggtitle(title)+
    theme_bw()+
    theme(legend.title = element_blank(),
          legend.position="none",
          aspect.ratio = aspect.ratio,
          plot.title = element_text(hjust = 0.5),
          panel.grid = element_blank(),
          axis.title = element_blank(),
          axis.text.y = element_blank(),
          axis.ticks.x = element_line(linewidth = 0.4),
          axis.ticks.y = element_blank(),
          axis.minor.ticks.x.bottom = element_line(linewidth = 0.2))+
    coord_fixed(xlim = c(xlims[1], xlims[2]))

  if(length(colors) == 1){
    p <- p+scale_color_manual(values = rep(colors, length(files)))
  }else{
    p <- p+scale_color_manual(values = colors)
  }

  if(plot.perc){
    p <- p+geom_text(data = labelMeta, mapping = aes(x = x, y = label, label = perc),
                     hjust = 0, nudge_x = nudge.perc.x, nudge_y = nudge.perc.y, inherit.aes = F)

    p <- p+geom_vline(aes(xintercept = lim_f), linetype="dashed")
  }

  if(plot.MFI){
    p <- p+geom_text(data = labelMeta, mapping = aes(x = x, y = label, label = MFI),
                     hjust = 0, nudge_x = nudge.MFI.x, nudge_y = nudge.MFI.y, inherit.aes = F)
    p <- p+geom_vline(aes(xintercept = sum$MFI[sum$sample == labels[1]]), linetype="dashed")

  }


  p

}
