#' Density plot for flow cytometry
#' @description
#' The function is designed to generate a multi-sample density plot for flow cytometry assay
#'
#' @param files standard CSV files generated by NovoExpress software
#' @param labels labels
#' @param channel channel name in the CSV file
#' @param xlims two numeric values, specifying the lower limit and the upper limit of the scale
#' @param title plot title
#' @param fills colors used to fill the density
#' @param colors colors
#' @param alpha alpha
#' @param fixed_ratio ratio of the x axis and y axis
#' @param pos.label position of labels
#'
#' @return a ggplot2 density plot
#' @export
#'
#' @examples
#' # none
#'
plotFC_multi <- function(files,
                         labels,
                         pos.label = 0.3,
                         channel,
                         xlims,
                         title = "xxx",
                         fills, colors, alpha,
                         fixed_ratio = 3){


  breaks <- xlims[2]-xlims[1]+1
  label.x <- 10^(xlims[1]+pos.label)
  xlims <- 10^xlims

  expList <- list()

  for (i in 1:length(files)) {
    expList[[i]] <- read.csv(file = files[i], sep = ",", header = T, fill = T, check.names = F) %>%
      tibble::add_column(sample = labels[i]) %>%
      subset(select = c("sample", channel)) %>%
      magrittr::set_colnames(c("sample", "exp"))
  }

  exps <- Reduce(rbind, expList)
  exps <- exps[exps$exp > 0, ]

  sum <- exps %>%
    dplyr::group_by(sample) %>%
    dplyr::summarise(MFI = mean(exp))


  exps$sample <- factor(exps$sample, levels = rev(labels))
  labelMeta <- data.frame(label = labels, x = label.x)

  p <- ggplot(exps, aes(x = exp, y = sample)) +
    ggridges::geom_density_ridges(aes(height = after_stat(scaled), fill = sample, color = sample),
                                  stat = "density",
                                  scale = 0.9,
                                  alpha = alpha,
                                  adjust =1/2,
                                  rel_min_height = 0) +
    scale_x_log10(expand = c(0,0),
                  limits = c(xlims[1], xlims[2]),
                  breaks = scales::breaks_log(n = breaks, base = 10),
                  labels = scales::label_log(base = 10),
                  guide = "axis_logticks")+
    scale_y_discrete(expand = c(0, 0,0, 1))+
    scale_fill_manual(values = fills)+
    scale_color_manual(values = colors)+
    geom_text(data = labelMeta, mapping = aes(x = x, y = label, label = label), hjust = 0, nudge_y = 0.8, inherit.aes = F)+
    ggtitle(title)+
    theme_bw()+
    theme(legend.title = element_blank(),
          legend.position="none",
          plot.title = element_text(hjust = 0.5),
          panel.grid = element_blank(),
          axis.title = element_blank(),
          axis.text.y = element_blank(),
          axis.ticks.x = element_line(linewidth = 0.4),
          axis.ticks.y = element_blank(),
          axis.minor.ticks.x.bottom = element_line(linewidth = 0.2))+
    coord_fixed(ratio = fixed_ratio)


  p

}
