#' Density plot for flow cytometry
#'
#' @description
#' The function is designed to generate a two-sample density plot for flow cytometry assay
#'
#'
#' @param file_con a standard CSV file of con sample generated by NovoExpress software
#' @param file_test a standard CSV file of test sample generated by NovoExpress software
#' @param label_con label of con sample
#' @param label_test label of test sample
#' @param channel channel name in the CSV file
#' @param gate high threshold, use 7 to indicate 10^7, the low threshold is automatically detected by the 0.99 quantile of the con sample
#' @param xlims two numeric values, specifying the lower limit and the upper limit of the scale
#' @param text.x text
#' @param lab.x x-axis label
#' @param lab.y y-axis label
#' @param title plot title
#' @param legend plot legend, the vaules can be "none"/"legend"
#' @param fills colors used to fill the density
#' @param colors colors
#' @param alpha alpha
#'
#' @return a ggplot2 density plot
#' @export
#'
#' @examples
#' # none
plotFC_2group <- function(file_con, file_test,
                          label_con = "con", label_test = "test",
                          channel, gate,
                          xlims,
                          text.x, lab.x = NULL, lab.y = "% of Max",
                          title = "xxx",
                          legend = "legend",
                          fills, colors, alpha){

  gate <- 10^gate
  breaks <- xlims[2]-xlims[1]+1
  xlims <- 10^xlims
  text.x <- 10^text.x



  exp1 <- read.csv(file = file_con, sep = ",", header = T, fill = T) %>%
    tibble::add_column(sample = label_con) %>%
    subset(select = c("sample", channel)) %>%
    magrittr::set_colnames(c("sample", "exp"))

  exp2 <- read.csv(file = file_test, sep = ",", header = T, fill = T) %>%
    tibble::add_column(sample = label_test) %>%
    subset(select = c("sample", channel)) %>%
    magrittr::set_colnames(c("sample", "exp"))


  lim_f <- quantile(exp1$exp, 0.99)

  perc <- length(exp2$exp[exp2$exp > lim_f & exp2$exp < gate])/length(exp2$exp)
  perc <- round(perc*100, 2)

  exps <- rbind(exp1, exp2)

  exps <- exps[exps$exp > 0, ]

  exps$sample <- factor(exps$sample, levels = c(label_con, label_test))

  p <- ggplot(exps, aes(x = exp, fill = sample, color = sample, group = sample))+
    geom_density(aes(y = after_stat(scaled)), alpha = alpha, adjust = 1/2)+
    annotate("segment", x = lim_f, y = 0.3, xend = gate, yend = 0.3, color = "black")+
    annotate("segment", x = lim_f, y = 0.28, xend = lim_f, yend = 0.32, color = "black")+
    annotate("segment", x = gate, y = 0.28, xend = gate, yend = 0.32, color = "black")+
    annotate("text", x = text.x, y = 0.4, label = paste0(label_test, "\n", perc, "%"))+
    labs(x = lab.x, y = lab.y)+
    ggtitle(title)+
    guides(color = legend, fill = legend)+
    scale_x_log10(expand = c(0,0),
                  breaks = scales::breaks_log(n = breaks, base = 10),
                  labels = scales::label_log(base = 10),
                  guide = "axis_logticks")+
    scale_y_continuous(expand = c(0,0),
                       limits = c(0,1.1),
                       breaks = seq(0,1, 0.2),
                       labels = scales::label_percent(suffix = ""))+
    scale_fill_manual(values = fills)+
    scale_color_manual(values = colors)+
    theme_bw()+
    theme(legend.title = element_blank(),
          aspect.ratio = 1,
          plot.title = element_text(hjust = 0.5),
          panel.grid = element_blank(),
          axis.ticks.x = element_line(linewidth = 0.4),
          axis.ticks.y = element_line(linewidth = 0.4),
          axis.minor.ticks.x.bottom = element_line(linewidth = 0.2))+
    coord_fixed(xlim = c(xlims[1], xlims[2]))

  p

}
