#' Gene expression plot for qPCR analysis
#'
#' @param file a table file of gene expression generated by QuantStudio software
#' @param gene genes to plot
#' @param geneLabel labels of genes
#' @param fill colors
#' @param groups groups
#' @param comparison comparison
#' @param style 1 or 2
#'
#' @return
#' @export
#'
#' @examples
plotQ_Dunn <- function(file, gene, geneLabel, fill, groups, comparison, style){
  require(rstatix)
  require(tidyverse)

  # load data
  exp <- read.table(file = file, sep = "\t", header = T, fill = T)
  exp <- data.frame(sample = exp$Sample.Name, gene = exp$Target.Name, rq = exp$RQ)
  exp <- na.omit(exp)
  exp$group <- gsub("_.*", "", exp$sample)

  # isolate interest gene and group
  exp_sub <- exp[exp$gene == gene & exp$group %in% groups,]
  exp_sub$group <- factor(exp_sub$group, levels = groups)

  # normalize
  mean_ctrl <- mean(exp_sub$rq[exp_sub$group == groups[1]])
  exp_sub$rq <- exp_sub$rq/mean_ctrl

  # stat
  res_dunn <- rstatix::dunn_test(exp_sub, rq ~ group)
  res_dunn <- res_dunn[res_dunn$group1 == groups[1],]
  res_dunn <- res_dunn[match(groups[comparison], res_dunn$group2),]
  res_dunn$ppos <- (1+comparison)/2

  max <- max(exp_sub$rq)*1.1
  res_dunn$y = cumprod(c(max, rep(1.1, length(comparison)-1)))
  res_dunn$p.adj <- paste0("p = ", round(res_dunn$p.adj, 3))

  if(style == 1){
    res_dunn$vline = res_dunn$y
    res_dunn$vline_end = res_dunn$y
  }
  if(style == 2){
    res_dunn$vline = res_dunn$y+0.02
    res_dunn$vline_end = res_dunn$y-0.02
  }

  exp_sum <- exp_sub %>%
    dplyr::group_by(group) %>%
    dplyr::summarise(mean = mean(rq),
              n = length(rq),
              sd = sd(rq),
              sem = sd/sqrt(n))

  p <- ggplot(exp_sum, aes(x = group, y = mean))+
    geom_bar(aes(fill = group), position = position_dodge(1), stat = "identity", color = "black", alpha = 0.6, width=0.6)+
    geom_errorbar(aes(x = group, ymin=mean-sem, ymax=mean+sem),
                  position = position_dodge(0.5), width=0.3, colour="black", alpha=0.9, linewidth =1)+
    geom_point(data = exp_sub, aes(y = rq, fill = group), shape = 21, size = 2, show.legend = FALSE, color = "black",
               position = position_jitterdodge(0.2, dodge.width = 1))+
    geom_segment(data = res_dunn, aes(x = group1, xend = group2, y = y, yend = y),linewidth = 0.3)+
    geom_segment(data = res_dunn, aes(x = group1, xend = group1, y = vline, yend = vline_end),linewidth = 0.3)+
    geom_segment(data = res_dunn, aes(x = group2, xend = group2, y = vline, yend = vline_end),linewidth = 0.3)+
    geom_text(data = res_dunn, aes(x = ppos-0.2, y = y*1.02, label = p.adj), size = 2, vjust = 0, hjust = 0, nudge_x = 0)+
    ggtitle(geneLabel)+
    scale_y_continuous(expand = c(0,0), limits = c(0,max(res_dunn$y)*1.1))+
    scale_x_discrete(expand = c(0,0))+
    scale_fill_manual(values = fill)+
    labs(x= "", y = "Relative mRNA expression")+
    theme_bw()+
    theme(legend.title = element_blank(),
          plot.title = element_text(hjust = 0.5),
          panel.grid = element_blank())

  p

}
